### ISSUE TITLE
Tracking Issue: Help us find Svelte regressions

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1040]
If anybody wants to help hunt for bugs caused by the switch in frontend frameworks, please open up the Vue version deployed at https://a4b0ce9f.graphite-editor.pages.dev#vue and the Svelte version deployed at <https://77a7866d.graphite.pages.dev#svelte> and search for any and all kinds of bugs or breakages related to anything from core functionality to UI edge cases. Comment here describing them.

- [x] Tab-navigation doesn't work between radio buttons (and likely others)
- [x] Color picker: New/Initial swap doesn't work as expected
- [x] Middle clicking to close a document tab
- [x] Number range sliders can't be dragged
- [x] Number range sliders jitter when dragged quickly
- [x] Resolve all comments starting with `// TODO: Svelte`
- [x] Replace docs and comments referencing Vue or Vue-specific concepts
- [x] Eyedropper tool breaks the editor
- [x] Editing text (e.g. layer name in Properties panel, textarea of text tool string) sticks its old value
- [x] Double clicking to rename a layer
- [x] Typing values into the ColorPicker doesn't update the New preview
- [x] Can't type a number into a number slider
- [ ] **In Vue:** Dropdown menu should allow clicking then closing, keeping a dotted border while the up/down arrow keys permit navigation (e.g. the blend mode menu) until the pointer enters the viewport when the border and key navigation go away.
  **In Svelte:** Arrow keys nudge the selected shape at the same time as changing the dropdown selection. Pointer entering viewport doesn't de-focus input.
**Suggested resolution:** Change it so we always redirect arrow keys to the backend except when an element is focused (`document.activeElement` is not the body element), we aren't able to otherwise use the arrow keys to scroll the active (or hovered, maybe?) panel (if it's scrollable), and we don't have a MenuList active which has its own custom arrow key navigation. (And other special cases?)
