### ISSUE TITLE
Replace legacy artboards with artboard nodes

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1171]
This is an example in our mockup of how artboards will work, with an Artboard node feeding into a layer, and the layer's vertical output being given to the graph's output:

![image](https://user-images.githubusercontent.com/4388688/234689702-e698978b-6da0-4902-9c21-a1f7dbca87bb.png)

```[tasklist]
- [x] #1205 - Add an Artboard node which takes `GraphicElement` input and produces `Artboard` or `ArtboardGroup` output data.
- [x] #1224 - These node-based artboards will need to live in a new node graph attached directly to the document itself, rather than being part of any one layer. This special node graph will become the singular node graph representing a whole document once the transition away from legacy layers is complete.
- [x] #1221 - The output from that special node graph is of type `ArtboardGroup` and it should enter the SVG output renderer and become an appropriately colored background rectangle as well as a definition for a [clipping mask](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Clipping_and_masking). (A checkered transparency background (defined in CSS) should also be included in the viewport, but in a way that causes it to be excluded from things that rasterize the artboard.)
- [x] #1222 - The Artboard tool will also need to be updated to work with node-based artboards, plus any editor features like the New Document dialog and *Document* > *Clear Artboards*.
- [x] #1223 - Legacy artboard code can be removed.
```

**Comment by Keavon** [comment]
Closed by 595f5462496dfc5fc702b0853d336898dde65c3e
