### ISSUE TITLE
Tracking Issue: Document graph migration MVP

### ISSUE THREAD

**Issue by TrueDoctor** [GraphiteEditor/Graphite#1394]
- [x] Pen tool doesn't place more than one point
- [x] Occasionally drawing with rectangle tool doesn't work/is offset
- [x] Thumbnails go over the entire node graph and break the click targets 
- [x] Thumbnails should display the left input, not the result of the composite
- [x] Placing on top of other artwork
- [x] Bounding boxes and hit testing
- [x] Rulers
- [x] Dragging in/pasting/importing images (#1418)
- [x] Each drawing tool selecting the layer it just created
- [x] Automatically insert the empty stack nodes (so the user doesn't accidentally disconnect and get an error). (#1445)
- [x] Preview vector data (#1446)
- [x] Grouping (with <kbd>Ctrl</kbd><kbd>G</kbd>) and ungrouping and the necessary graph rearrangement (#1176)
- [x] Migrate demo artwork (#1459)
- [x] Migrate tests to node graph so CI passes again (#1456 #1459)
- [x] Drag an image into the graph and fix popup when dragging into document. (#1459)
- [x] Naive placement of layers in artboards (#1459)
- [x] Opacity and blend mode settings on layers (#1459)
- [x] Fix performance regressions that make it slow to interact with the editor (#1477)
- [x] Fix collapsing/expanding layers (currently crashes) and hiding with the eye icon (currently does nothing) (#1481)
- [x] Fix bug where the artboard isn't centered when creating a new document (instead it starts in the top left) (#1473)
- [x] Fix wireframe view mode (#1473)
- [x] Fix bug where layer click targets are offset by the Transform node from rendered location (#1473)
- [x] G/R/S shortcuts (#1473)
- [x] Fix bug where node graph doesn't change after switching document tabs
    - [x] Fix bug where connection links get tangled upon switching document tabs
- [x] Fix the tremendous volume of JS console warning/error spam (#1484)
    - [x] Clean up all the FrontendMessages being sent to the JS but lacking a subscribed handler (#1484)
- [x] Fix bug with how a Transform node feeding into an Artboard node works [(video)](https://files.keavon.com/-/OutstandingColossalEskimodog/capture.mp4) (#1484)
    - [x] Fix bug where a Transform node feeding into an Artboard node causes the artboard's selection outline to be misaligned from the artboard itself (#1484)
- [x] #1485
- [x] <kbd>Ctrl</kbd><kbd>A</kbd> should not select the artboard
- [x] #1488
- [x] Properties panel should show the input chain if a Layer is selected, and if a node is in a chain, it should show all others in that chain
- [x] Port *File* > *Export* to document nodes (#1495)
- [x] Fix the graph's "Preview" button (or <kbd>Alt</kbd>-click on a node/layer) not working on layers, only nodes; desired behavior: display the stack's vertical (top) output (#1496)
- [x]  Fix how rearranging layers throws `DocumentError: LayerNotFound` console errors (but otherwise works) (#1497)
- [x]  Fix crash when drawing after deleting all artboards (#1497)
- [x] Having no artboards (infinite canvas) should show a white background (#1497)
- [x] Serve the demo artwork from each deploy, not the GH master branch (#1494)
- [x] Reenable nudging (and nudge-resizing) with arrow keys (#1501)
- [x]  *Document* > *Clear Artboards* crashes (#1502)
- [x] Fix how any interaction with the Select tool causes the document to change (which makes the `*` appear because the file is no longer saved) (#1509)
- [x] Setting opacity and blend mode for selected layers at top of Layers panel (#1506)
- [x] Tools
  - [x] Select (#1433)
  - [x] Artboard (closes #1222 and closes #1223)
  - [x] Colour picker
  - [x] Fill
  - [x] Gradient
  - [x] Path
  - [x] Pen
  - [x] Freehand
  - [x] Spline
  - [x] Line
  - [x] Rectangle
  - [x] Circle
  - [x] Shape
  - [x] Text (#1435)
  - [x] Frame
  - [x] Imaginate (#1512)
  - [x] Brush (#1473)
- [x] Deploy the next production release 🎉 (and remember to delete the old demo artwork and remove the `-v2` suffix from the new ones)

**Comment by 0HyperCube** [comment]
Almost all of the tasks here are done - I think we can probably close this issue and break up the remaining tasks into separate issues @Keavon.

**Comment by 0HyperCube** [comment]
@Keavon I did the select tool star in #1509.

**Comment by Keavon** [comment]
Thank you for helping with that! I just broke out all the remaining issues, so it's just a matter of landing your opacity/blend modes one (I'm starting to code reviewing it in moment) and fixing Imaginate tonight with TrueDoctor, then doing the deploy 🚀.
