### ISSUE TITLE
Tracking Issue: Quick measurement overlays while holding the Alt key

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#1896]
- [x] First basic implementation (#1894)
- [x] Improvements to match the spec described below (#2147)
- [x] Tidy up the number text alignment and decimal precision (#2155)
- [ ] Make it work when the layers are rotated and skewed (#2396)

---

When holding the <kbd>Alt</kbd> key with a layer (or multiple) selected, while hovering over another layer (or group), an overlay should appear visualizing the AABB of both the selected and hovered layers, with lines and distance numbers (in document coordinates) between them as shown below.

When the document is viewed with a tilt in the viewport PTZ navigation, the lines become angled but the text labels stay upright for readability.

Here are, I believe, all the scenarios. The three diagrams with text do care about which is the selected layer and which is the hovered layer; all the others are drawn the same in either order, so it doesn't matter which is the selected or hovered one. The two colored boxes represent AABBs, not actual shapes in the artwork— those should be drawn with a blue outline around both their AABBs.

| Scenarios |
| - |
| <strong>Terminology definitions:</strong><br /><br />- "Boxes overlap along 0/1/2 axes" means extruding the box's edge infinitely left/right, or up/down, would hit the other box<br />- "0/1/2 of their centerlines cross the other boxes" means extending both box's center points infinitely left/right, or up/down, would hit the other box<br />- "Along axis A/B" means either the X and Y, or the Y and X, axes<br />- "box A/B" means either one particular box and its opposite, or the reverse<br /><br /> |
| Boxes overlap along 0 axes:<br /><br />![image](https://github.com/user-attachments/assets/4f1e6752-f4c4-4494-8b76-c34b3903f20b) |
| Boxes overlap along 1 axis and 0 of their centerlines cross the other boxes:<br /><br />![image](https://github.com/user-attachments/assets/3dd9bbc2-a55a-4465-b5bb-7c9bd1511f15) |
| Boxes overlap along 1 axis and 2 of their centerlines cross the other boxes:<br /><br />![image](https://github.com/user-attachments/assets/79bb251b-31bd-49d6-90a4-cdc4518715fb) |
| Boxes overlap along 1 axis and 1 of their centerlines cross the other boxes:<br /><br />![image](https://github.com/user-attachments/assets/2fdd2181-93f8-4780-b7d5-afdee3f9ab09) |
| Boxes overlap along 2 axes and:<br />- Along axis A, box A has 1 edge line cross box B while box B has 1 edge line cross box A<br />- Along axis B, box A has 1 edge line cross box B while box B has 1 edge line cross box A<br /><br />![capture](https://github.com/user-attachments/assets/e73f8059-4c04-4859-829a-eec18d80226d) |
| Boxes overlap along 2 axes and:<br />- Along axis A, box A has 1 edge line cross box B while box B has 1 edge line cross box A<br />- Along axis B, box A has 2 edge lines cross box B while box B has 0 edge lines cross box A<br /><br />![capture](https://github.com/user-attachments/assets/98f2921b-827b-41db-acf1-2aedbfb0cfb3) |
| Boxes overlap along 2 axes and:<br />- Along axis A, box A has 2 edge lines cross box B while box B has 0 edge lines cross box A<br />- Along axis B, box A has 0 edge lines cross box B while box B has 2 edge lines cross box A<br /><br />![capture](https://github.com/user-attachments/assets/b097c8aa-e205-4c2d-8182-1f5e6c96ffa1) |
| Boxes overlap along 2 axes and:<br />- Along axis A, box A has 2 edge lines cross box B while box B has 0 edge lines cross box A<br />- Along axis B, box A has 1 edge line cross box B while box B has 1 edge line cross box A<br /><br />![capture](https://github.com/user-attachments/assets/55f15296-86d9-42cc-814a-0c2f0beadfa2) |
|Boxes overlap along 2 axes and:<br />- Along axis A, box A has 2 edge lines cross box B while box B has 0 edge lines cross box A<br />- Along axis B, box A has 2 edge lines cross box B while box B has 0 edge lines cross box A<br /><br />![capture](https://github.com/user-attachments/assets/e31c5473-fc33-4772-a600-fe33e94270ab) |

Diagram source file: [Quick Measurement Overlays Design.graphite.txt](https://github.com/user-attachments/files/16493997/Quick.Measurement.Overlays.Design.graphite.txt)

**Comment by singhutsav5502** [comment]
Hi, @Keavon .

**Comment by singhutsav5502** [comment]
Hi, @Keavon opened a PR  #2155  for sub-task 3.

**Comment by singhutsav5502** [comment]
Hi, @Keavon do you happen to know of any tool(s) that show similar functionality/features especially for rotated objects. I think it would be best to have some examples on expected functionality for rotated shapes before i work any further on this issue especially  since the existing axis crossing and center line crossing logic may not work as expected when relative rotation is involved.

**Comment by Keavon** [comment]
Please ping me again if I forget to respond with an answer in the next day or two. It'll take me a little while to prepare a spec for you, but you are definitely right to ask because it's nontrivial what should happen here.

**Comment by singhutsav5502** [comment]
> Please ping me again if I forget to respond with an answer in the next day or two. It'll take me a little while to prepare a spec for you, but you are definitely right to ask because it's nontrivial what should happen here.

okay!

**Comment by singhutsav5502** [comment]
Hi, @Keavon just a quick ping for the specs.

**Comment by Keavon** [comment]
Still haven't gotten to it yet, sorry. Ping me in a few more days if I still haven't.

**Comment by Keavon** [comment]
@singhutsav5502 Ok, I have an answer for you, thanks for your patience.

The quick measurement overlay should occur in the rotational space of the selected layer.

Then, if the hovered layer has a different rotation compared to the selected layer, it should draw blue overlays of an axis-aligned bounding box (where the axis-alignment is in the space of the selected layer) around the hovered layer. That way, the quick measurement can measure a straight line from the selected layer to this bounding box of the hovered layer, with both sharing the same rotation in relation to each other.

References to the "selected layer" in the previous paragraph technically mean "the transform cage's bounding box". Because if you have multiple layers selected and they don't share the same rotation, the transform cage will use the rotation of the top layer for the transform cage. It is the transform cage which counts as the "selected layer" in the context of the previous paragraph.

**Comment by singhutsav5502** [comment]
> [@singhutsav5502](https://github.com/singhutsav5502) Ok, I have an answer for you, thanks for your patience.

> Then, if the hovered layer has a different rotation compared to the selected layer, it should draw blue overlays of an axis-aligned bounding box (where the axis-alignment is in the space of the selected layer) around the hovered layer. That way, the quick measurement can measure a straight line from the selected layer to this bounding box of the hovered layer, with both sharing the same rotation in relation to each other.


I see, so the AABB drawn around the Hovered layer runs parallel to the "selected layer" transform cage? and there's a straight line connecting the "selected layer" transform cage to the drawn AABB ?

**Comment by Keavon** [comment]
Yes, exactly.

Also please be aware of the situation where the layer is skewed. Currently this happens, which isn't desired, and it completely breaks apart in most other positions (I had to find a nice position for the screenshot):

![capture](https://github.com/user-attachments/assets/00760c06-d9a6-4771-8215-ab1a5ba24299)

**Comment by singhutsav5502** [comment]
> Yes, exactly.
> 
> Also please be aware of the situation where the layer is skewed. Currently this happens, which isn't desired, and it completely breaks apart in most other positions (I had to find a nice position for the screenshot):
> 
> ![capture](https://github.com/user-attachments/assets/00760c06-d9a6-4771-8215-ab1a5ba24299)

Okay, is there a particular function that defines how the AABB is affected by the skew transform?

**Comment by Keavon** [comment]
On both ends of the quick measure, we want the AABB in the rotational space of the transform cage. As the name AABB implies, "box" shouldn't be a parallelogram. So you will want the AABB around the parallelogram on the selected (transform cage) and hovered ends of the measurement, where both of those boxes have parallel edges with each other.

**Comment by Keavon** [comment]
By the way, there's no need to quote my message every time you reply, that just makes this comment section longer than it needs to be. You can either `@`mention the person or check from the "Participants" list at the top right sidebar of the issue to see who will receive notifications, so in this case there's three of us receiving notifications to all comments. Quoting doesn't even send notifications. It's meant for quoting a specific snippet to type a response to, not just repeating the whole message. Just wanted to let you know.

**Comment by singhutsav5502** [comment]
![Image](https://github.com/user-attachments/assets/1fb44b06-acf3-4915-9c6e-813e187b4b19)

using the path tool to skew the selected layer seems to retain the original functionality, how do i go about skewing the "layer" ?

**Comment by Keavon** [comment]
If you just moved the points with the Path tool, that isn't skewing. Use the Select tool to rotate it, scale it along one axis with `S` and `X`, then un-rotate it.

**Comment by singhutsav5502** [comment]
Hi, in case of the below case of a skewed rectangle, which one of the following 2 would serve as the expected functionality?
The first one seems to be following the `minimum x value` of the skewed rectangle, which technically based on the definition of AABB  should be correct.

![Image](https://github.com/user-attachments/assets/3e24f9e8-ef80-4128-b688-c2a48490f156)

![Image](https://github.com/user-attachments/assets/85736a39-4aff-42b2-9220-0425892a8f83)

**Comment by Keavon** [comment]
The first image is correct. I don't understand your second comment's question so I can't answer it.

**Comment by Keavon** [comment]
@singhutsav5502 just checking in :)

**Comment by singhutsav5502** [comment]
Hi, still working on the issue. Will try to figure out what's causing the issue with skewed objects first.

**Comment by singhutsav5502** [comment]
Regarding the rotation behavior for the quick layer tool, it seems the reason it isn't already working is similar to the problem with the `skewed` shapes. Since the logic itself is built on the assumption that the bounds represent AABBs then there is no reason for the existing cases to stop functioning in case of rotated shapes since we will still be dealing with their AABBs and not their actual transformed bounds. I will try nd come up with a solution as discussed in the discord channel earlier, it seems coming up with a method to find proper `selected and hovered bounds` for the shapes*after* taking in consideration the rotation and scale should fix both issues.

**Comment by singhutsav5502** [comment]
@Keavon opened a PR for the final checklist item.
