### ISSUE TITLE
Tracking Issue: Announce Graphite to the world

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#193]
Once we reach the goal of implementing most of the important tools needed to provide artists a reasonably pain-free experience creating art, then we are ready to officially announce the product to the world. This should hopefully grow interest in the project, contributions from more Rust and web developers, and even users (plus those sweet sweet ⭐s on GitHub).

Possible communities to announce to includes /r/rust_gamedev, /r/rust and other Rust communities, graphic design communities, web design communities, [Pixls.us](https://discuss.pixls.us), Blender-related communities, VFX-related communities, and others (post suggestions as a comment). Websites include Reddit, Twitter, forums, news outlets.

Launching the first versioned release, how exciting!

- [x] Polish the editor
- [ ] Further improve the website
- [ ] Improve the project readme
- [ ] Film and edit a sizzle reel trailer

**Comment by Keavon** [comment]
I may reopen this issue when the time is right, but we're still going to want to at least get a desktop app, hardware acceleration, and some raster completed before committing to a proper "launch"/"announcement" instead of incremental growth and communications.
