### ISSUE TITLE
Tracking Issue: GPU integration

### ISSUE THREAD

**Issue by Keavon** [GraphiteEditor/Graphite#2168]
```[tasklist]
# GPU integration
- [ ] #1239
- [ ] #1240
- [ ] #1241
- [ ] #1255
- [ ] #1258
- [ ] #1259
- [ ] #1308
- [x] Modify transform node to support passing a short-circuit input
- [ ] #1307
- [ ] #1295
- [ ] #1293
- [ ] #1296
- [x] Investigate if we can manually influence the limits and have that actually affect something (blocked by WebGPU Device Limits gfx-rs/wgpu#3299?)
- [ ] #1539
- [ ] #1299
- [ ] #1298
- [ ] #1300
- [ ] #1303
- [ ] Add feature gate to only display GPU-based nodes when wgpu is available
- [ ] Add documentation + tests + improve the API
- [ ] Modularize GPU blend mode as a merge node
- [ ] Add nodes for updating existing buffers
- [ ] Rasterize vector content at the appropriate time in the graph
- [ ] Integrate and use the quality level factor as part of the adaptive resolution render pipeline
```

<details>
<summary>
