### ISSUE TITLE
Artboard organization

### ISSUE THREAD

**Issue by bjorn3** [GraphiteEditor/Graphite#539]
* [x] Allow moving artboards together with their contents. Currently moving artboards doesn't move their contents.
* [x] Show which layer is part of which artboard.
* [x] When artboards overlap don't show the things drawn beneath the top artboard.
* [ ] Add an option to organize artboards in a grid or other pattern - similar to #860.
* [ ]  Placing layers in correct artboard based on location (#1507)
* [ ] Transferring layers between artboards when dragged from one to the other upon release (#1507)

**Comment by 0HyperCube** [comment]
Do we also want to show the artboards in the properties panel so users can see which layers are in each artboard?
![screenshot-4](https://user-images.githubusercontent.com/78500760/164210484-fc2f97a6-07de-4792-a87b-fcad2085be1e.png)
(Screenshot from [Akira](https://github.com/akiraux/Akira))

**Comment by Keavon** [comment]
It'll require some effort to make a concept of artboards owning layers. It's also an open question still how exactly that will work from a design perspective, especially once nodes are the basis for the document format. I would probably suggest that we aim to get nodes working in the next few months rather than writing code that will be ripped out by then anyways.

For the way the node graph works, folders == documents == subgraphs. I don't yet know how artboards fit into that picture, but maybe artboards are a special type of folder? Or maybe they are a property on a folder? Or maybe they are all defined through a property on the containing document? I don't have all the answers yet but I feel like we might need to try a few things out to see how they feel after we get the basics of the node system implemented by porting over existing layers and folders into nodes.

**Comment by Keavon** [comment]
Duplicate of the issues mentioned in the bullet points.
